Add MinVersion field to muxer configs.
gravwell/gravwell pull request #1480
Opened 2024-12-13 19:31 UTC by john-floren-gravwell

Muxer will refuse to connect to any indexer reporting an API version lower than that specified in the config, thus if you intend to use ditto you might say:

		igCfg := ingest.UniformMuxerConfig{
			[...]
			MinVersion:         ingest.MINIMUM_DITTO_VERSION,
			[...]
		}
		igst, _ = ingest.NewUniformMuxer(igCfg)

An insufficient API version is treated as non-fatal; the muxer will attempt to reconnect to that indexer periodically, on the assumption that it will eventually be updated.

As long as one indexer meets the minimum version requirement, you will be able to use the muxer as usual. If not, the muxer will never go hot.

2024-12-13 19:32 UTC, john-floren-gravwell commented
Addresses #1442

2024-12-13 21:21 UTC, david-fritz-gravwell approved these changes
LGTM

2024-12-14 20:57 UTC, kris-watts-gravwell requested changes
It looks like this will always fail if min version is not set.   I would argue we only do that check if minVersion is set

2024-12-14 20:57 UTC, kris-watts-gravwell commented on ingest/muxer.go
> +		if ig.ew.serverVersion < im.minVersion {
I think this needs an additional check.  

If minVersion > 0 && serverVersion < minVersion

2024-12-14 21:58 UTC, kris-watts-gravwell approved these changes
LGTM

2024-12-14 21:58 UTC, merged

2024-12-14 21:59 UTC, kris-watts-gravwell commented on ingest/muxer.go
> +		if ig.ew.serverVersion < im.minVersion {
yes I am a moron and yes I realized it several hours later.