Unify generators into a single program
gravwell/gravwell pull request #509
Opened 2022-09-28 23:24 UTC by john-floren-gravwell

This gathers all the generator types into a single program. Once a lot of the accessory stuff is deduplicated, each generator tends to become a very small function.

2022-09-29 01:14 UTC, kris-watts-gravwell requested changes
very nice.  I think we can delete the old ones and just have a "generator", no?

2022-09-29 15:43 UTC, david-fritz-gravwell requested changes

2022-09-29 15:43 UTC, david-fritz-gravwell commented on generators/unifiedGenerator/binary.ax
> +# Extraction defintion for the csv generator with everything
```suggestion
# Extraction defintion for the binary generator with everything
```

2022-10-03 18:04 UTC, kris-watts-gravwell approved these changes
LGTM

2022-10-03 18:25 UTC, david-fritz-gravwell approved these changes
Lgtm

2022-10-03 18:25 UTC, merged