track HEC IDs per request ID
gravwell/gravwell pull request #664
Opened 2023-03-20 23:52 UTC by john-floren-gravwell

Addresses #608

2023-03-21 00:40 UTC, kris-watts-gravwell requested changes
Need to release lock before going to the network on the writeAck command

2023-03-21 00:40 UTC, kris-watts-gravwell commented on ingesters/HttpIngester/hec.go
> +	json.NewEncoder(w).Encode(ack{
I think we need to release the acklock before writing to the network.  A slow client would block all other clients

2023-03-21 18:31 UTC, john-floren-gravwell commented
ptal

2023-03-22 19:08 UTC, kris-watts-gravwell approved these changes
LGTM

2023-03-22 19:08 UTC, merged