fixing queue depth on S3 ingester
gravwell/gravwell pull request #999
Opened 2024-02-08 23:51 UTC by kris-watts-gravwell

fix depth and retry on deletes

2024-02-08 23:53 UTC, david-fritz-gravwell requested changes
LGTM

2024-02-08 23:53 UTC, david-fritz-gravwell commented on sqs_common/sqs.go
> +		_, err = s.svc.DeleteMessageBatch(deleter)
I would add a second error message here saying the retry failed, and warn that "message may be duplicated later"

2024-02-09 00:01 UTC, ashnwade approved these changes

2024-02-09 00:02 UTC, david-fritz-gravwell approved these changes
LGTM

2024-02-09 00:07 UTC, merged